apiVersion: v1
kind: Secret
metadata:
  name: travel-card-api-secrets
  namespace: travelcard
type: Opaque
stringData:
  DATABASE_USERNAME: agoda_wallet
  DATABASE_PASSWORD: agoda_wallet
  WISE_CLIENT_SECRET: sandbox-secret
  WISE_SUBSIDY_CLIENT_SECRET: sandbox-secret-subsidy
  VAULT_TOKEN: dev-root-token
